# ProofBox Configuration

debug_mode: true

call_rate_seconds: 1

temp_sense_id: '28-051686ec5dff'

# Temperature settings (Fahrenheit)

alarm_low_temp: 32.0
alarm_high_temp: 95.0

min_temp: 70.0
max_temp: 80.0 
